(function () {
  "use strict";
  var state = { vehicles: [], selectedId: "", equipment: [], loading: false, error: "", editingId: "" };
  var requestSerial = 0;
  function esc(value) { return String(value == null ? "" : value).replace(/[&<>"']/g, function (c) { return ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;", "'":"&#39;"})[c]; }); }
  function api(path, options) { if (!window.LMServer?.request) return Promise.reject(new Error("Server non disponibile.")); return window.LMServer.request(path, options); }
  function selected() { return state.vehicles.find(function (v) { return v.id === state.selectedId; }) || state.vehicles[0] || null; }
  function displayName(vehicle) { return vehicle.plate || vehicle.name; }
  function setError(message) { state.error = message || ""; var node = document.querySelector("#vehiclesError"); if (node) node.textContent = state.error; }
  function paint() {
    var content = document.querySelector("#appContent");
    if (!content || !content.querySelector(".fleet-page")) return;
    var oldSelected = content.querySelector(".fleet-vehicle-card.selected")?.dataset.id;
    var draft = oldSelected === state.selectedId ? { plate: content.querySelector("#fleetPlate")?.value, notes: content.querySelector("#fleetNotes")?.value } : null;
    var focused = document.activeElement?.id;
    var cursor = focused === "fleetPlate" || focused === "fleetNotes" ? document.activeElement.selectionStart : null;
    content.innerHTML = render();
    if (draft) {
      if (draft.plate != null) content.querySelector("#fleetPlate").value = draft.plate;
      if (draft.notes != null) content.querySelector("#fleetNotes").value = draft.notes;
      if (focused === "fleetPlate" || focused === "fleetNotes") {
        var field = content.querySelector("#" + focused);
        field.focus();
        if (cursor != null) field.setSelectionRange(cursor, cursor);
      }
    }
  }
  function renderEquipment(vehicle) {
    if (!vehicle) return '<div class="fleet-empty">Seleziona un mezzo per vedere le attrezzature.</div>';
    var rows = state.equipment.length ? state.equipment.map(function (item) {
      return '<div class="fleet-equipment-row"><div><strong>' + esc(item.name) + '</strong><small>' + esc(item.category || "Attrezzatura") + (item.code ? " · " + esc(item.code) : "") + (item.serial_number ? " · SN " + esc(item.serial_number) : "") + '</small></div><div class="fleet-equipment-qty">' + esc(item.quantity || 1) + '</div><button class="button button-quiet button-small" data-action="fleet-edit-equipment" data-id="' + esc(item.id) + '">Modifica</button></div>'; }).join("") : '<div class="fleet-empty">Nessuna attrezzatura associata.</div>';
    return '<div class="fleet-equipment-list">' + rows + '</div>';
  }
  function render() {
    var vehicle = selected();
    var cards = state.vehicles.length ? state.vehicles.map(function (v) { return '<button class="fleet-vehicle-card ' + (v.id === (vehicle && vehicle.id) ? "selected" : "") + '" data-action="fleet-select" data-id="' + esc(v.id) + '"><span class="fleet-vehicle-icon">▣</span><span><strong>' + esc(displayName(v)) + '</strong><small>' + (v.plate ? "Targa registrata" : "Targa non impostata") + '</small></span><b>' + esc(v.equipment_lines || 0) + '</b></button>'; }).join("") : '<div class="fleet-empty">Nessun mezzo registrato.</div>';
    var detail = vehicle ? '<div class="fleet-detail"><div class="fleet-detail-head"><div><span class="eyebrow">MEZZO SELEZIONATO</span><h2>' + esc(displayName(vehicle)) + '</h2></div><span class="status-pill status-completata">' + (!vehicle.active ? "Inattivo" : "Attivo") + '</span></div><div class="fleet-fields"><label class="field-label">Targa<input class="text-input" id="fleetPlate" value="' + esc(vehicle.plate || "") + '" placeholder="Es. AB123CD" /></label><label class="field-label">Note<textarea class="text-input" id="fleetNotes" rows="3" placeholder="Note operative">' + esc(vehicle.notes || "") + '</textarea></label></div><div class="dialog-actions"><span class="dialog-spacer"></span><button class="button button-primary" data-action="fleet-save-vehicle">Salva mezzo</button></div><div class="fleet-section-head"><div><span class="eyebrow">DOTAZIONE</span><h3>Attrezzature associate</h3></div><button class="button button-quiet" data-action="fleet-new-equipment">+ Nuova attrezzatura</button></div>' + renderEquipment(vehicle) + '</div>' : '<div class="fleet-detail fleet-empty">Seleziona un mezzo.</div>';
    return '<section class="fleet-page">' + '<div class="page-heading"><div><span class="eyebrow">GESTIONE OPERATIVA</span><h1>Mezzi</h1><p class="page-subtitle">Furgoni, attrezzature e stato operativo.</p></div><div class="heading-note">Dati dal server Lumen System</div></div>' + '<p id="vehiclesError" class="wh-error" role="alert">' + esc(state.error) + '</p>' + '<div class="fleet-layout"><div><div class="fleet-vehicle-grid">' + cards + '</div><button class="button button-quiet fleet-refresh" data-action="fleet-refresh">Aggiorna elenco</button></div>' + detail + '</div></section>';
  }
  async function loadEquipment(id) { var serial = ++requestSerial; try { var payload = await api("/equipment?vehicle_id=" + encodeURIComponent(id)); if (serial !== requestSerial || state.selectedId !== id) return; state.equipment = payload.equipment || []; setError(""); } catch (error) { if (serial === requestSerial) setError(error.message || "Impossibile caricare le attrezzature."); } finally { if (serial === requestSerial) paint(); } }
  async function load() { var serial = ++requestSerial; state.loading = true; try { var payload = await api("/vehicles"); if (serial !== requestSerial) return; state.vehicles = payload.vehicles || []; if (!state.selectedId || !state.vehicles.some(function(v){return v.id===state.selectedId;})) state.selectedId = state.vehicles[0]?.id || ""; state.equipment = []; paint(); if (state.selectedId) { var id = state.selectedId; var e = await api("/equipment?vehicle_id=" + encodeURIComponent(id)); if (serial !== requestSerial || state.selectedId !== id) return; state.equipment = e.equipment || []; } setError(""); } catch (error) { if (serial === requestSerial) setError(error.message || "Impossibile caricare i mezzi."); } finally { if (serial === requestSerial) { state.loading = false; paint(); } } }
  async function saveVehicle() { var v = selected(); if (!v) return; var plate = document.querySelector("#fleetPlate")?.value.trim() || null; var notes = document.querySelector("#fleetNotes")?.value.trim() || null; try { var response = await api("/vehicles/" + encodeURIComponent(v.id), { method: "PATCH", body: JSON.stringify({ version: v.version, plate: plate, notes: notes }) }); var updated = response.vehicle; if (updated) { state.vehicles = state.vehicles.map(function (item) { return item.id === updated.id ? Object.assign({}, item, updated) : item; }); if (state.selectedId === updated.id) paint(); } setError(""); } catch (e) { setError(e.message); } }
  async function saveEquipment(id) { var form = document.querySelector("#fleetEquipmentForm"); if (!form) return; var body = { vehicle_id: selected().id, name: form.elements.name.value.trim(), category: form.elements.category.value.trim(), code: form.elements.code.value.trim(), serial_number: form.elements.serial_number.value.trim(), quantity: Number(form.elements.quantity.value || 1), notes: form.elements.notes.value.trim() }; try { await api(id ? "/equipment/" + encodeURIComponent(id) : "/equipment", { method: id ? "PATCH" : "POST", body: JSON.stringify(id ? Object.assign(body, { version: state.equipment.find(function(x){return x.id===id;})?.version }) : body) }); state.editingId = ""; await load(); } catch (e) { setError(e.message); } }
  function equipmentForm(id) { var item = state.equipment.find(function(x){return x.id===id;}) || {}; var detail = document.querySelector(".fleet-detail"); if (!detail) return; var block = document.createElement("div"); block.className = "fleet-form-card"; block.innerHTML = '<form id="fleetEquipmentForm"><div class="fleet-section-head"><div><span class="eyebrow">DOTAZIONE</span><h3>' + (id ? "Modifica attrezzatura" : "Nuova attrezzatura") + '</h3></div></div><div class="fleet-form-grid"><label class="field-label">Nome<input class="text-input" name="name" required value="' + esc(item.name || "") + '"></label><label class="field-label">Quantità<input class="text-input" type="number" min="1" name="quantity" value="' + esc(item.quantity || 1) + '"></label><label class="field-label">Categoria<input class="text-input" name="category" value="' + esc(item.category || "") + '"></label><label class="field-label">Codice<input class="text-input" name="code" value="' + esc(item.code || "") + '"></label><label class="field-label">Seriale<input class="text-input" name="serial_number" value="' + esc(item.serial_number || "") + '"></label><label class="field-label">Note<input class="text-input" name="notes" value="' + esc(item.notes || "") + '"></label></div><div class="dialog-actions"><button class="button button-quiet" type="button" data-action="fleet-cancel-equipment">Annulla</button><button class="button button-primary" type="submit">Conferma</button></div></form>'; detail.appendChild(block); block.querySelector("form").addEventListener("submit", function(e){ e.preventDefault(); saveEquipment(id); }); block.scrollIntoView({ behavior: "smooth", block: "nearest" }); }
  document.addEventListener("click", function (event) { var t = event.target.closest("[data-action]"); if (!t) return; var a=t.dataset.action; if (a === "fleet-select") { if (state.selectedId === t.dataset.id) return; state.selectedId=t.dataset.id; state.equipment=[]; paint(); loadEquipment(state.selectedId); } else if (a === "fleet-refresh") load(); else if (a === "fleet-save-vehicle") saveVehicle(); else if (a === "fleet-new-equipment") equipmentForm(""); else if (a === "fleet-edit-equipment") equipmentForm(t.dataset.id); else if (a === "fleet-cancel-equipment") t.closest(".fleet-form-card")?.remove(); });
  window.renderVehiclesPage = render;
  window.loadVehiclesPage = load;
})();

